<a href="https://colab.research.google.com/github/Mayurisalunke98/Hello/blob/main/Numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = [1,2,3,"Mayuri",True]
a

[1, 2, 3, 'Mayuri', True]

In [ ]:
!pip install numpy

In [ ]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
type(a)

list

In [ ]:
res = [i**2 for i in a] #[] #res = result
res

[1, 4, 9, 16, 25]

In [ ]:
import numpy as np


In [ ]:
b = np.array(a)
print(b)

[1 2 3 4 5]


In [ ]:
type(b)

numpy.ndarray

In [ ]:
print(b**2)

[ 1  4  9 16 25]


In [ ]:
type(list(range(1000000)))

list

In [ ]:
l = list(range(1000000)) #python list

In [ ]:
%timeit [i**2 for i in l] #Without the optimal numpy library

315 ms ± 12.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
l = np.array(range(1000000)) #element wise operation in numpy #C programming

In [ ]:
%timeit l**2

1.17 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
#Dimension #Shape

In [ ]:
arr1 = np.array(range(1000000))
arr1

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [ ]:
arr1.ndim #number of dimension #directions

1

In [ ]:
arr1.shape #shape #size. (column,)

(1000000,)

In [ ]:
arr1.shape[0]

1000000

In [ ]:
arr2 = np.array([[1,2,3,],[4,5,6,],[10,11,12]])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape #(row,column)

(3, 3)

In [ ]:
#(d,r,c)
array_drc = np.array([
    [  # Depth 0
        [1, 2, 3, 4],  # Row 0
        [5, 6, 7, 8],  # Row 1
        [9, 10, 11, 12] # Row 2
    ],
    [  # Depth 1
        [13, 14, 15, 16],  # Row 0
        [17, 18, 19, 20],  # Row 1
        [21, 22, 23, 24]   # Row 2
    ]
])

print("3D Array (Depth, Rows, Columns):")
print(array_drc)
print("Shape:", array_drc.shape)


3D Array (Depth, Rows, Columns):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [ ]:
array_drc.ndim

3

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])


In [ ]:
a.ndim

1

In [ ]:
a.shape

(8,)

In [ ]:
print(a.ndim, a.shape)

1 (8,)


In [ ]:
#np.arange()

In [ ]:
list(range(1,5))

[1, 2, 3, 4]

In [ ]:
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [ ]:
list(range(1,5,2))

[1, 3]

In [ ]:
arr2_step = np.arange(1,5,2)
arr2_step

array([1, 3])

In [ ]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
list(range(1,5,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
import numpy as np
arr = np.arange(5)
arr[2:4] = 0 #slicing
print(arr)

[0 1 0 0 4]


In [ ]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr[2:4]

array([2, 3])

In [ ]:
arr[2:4]= 0

In [ ]:
arr

array([0, 1, 0, 0, 4])

In [ ]:
#type conversation

In [ ]:
arr4 = np.array([1,2,3,4])
arr4

array([1, 2, 3, 4])

In [ ]:
arr4.dtype

dtype('int64')

In [ ]:
arr5 = np.array([1,2,3,4.0]) #conversion
arr5

array([1., 2., 3., 4.])

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
np.array(["Mrityunjoy",1,2,3])

array(['Mrityunjoy', '1', '2', '3'], dtype='<U21')

In [ ]:
arr5 = np.array([1, 2, 3, 4])
arr5

array([1, 2, 3, 4])

In [ ]:
arr5 = np.array([1, 2, 3, 4], dtype="float") #first method
arr5

array([1., 2., 3., 4.])

In [ ]:
np.array(["Shivank","Bipin","Ritwik"],dtype="float")

ValueError: could not convert string to float: 'Shivank'

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr


array([10, 20, 30, 40, 50])

In [ ]:
arr = arr.astype('float64') #second type
print(arr)

[10. 20. 30. 40. 50.]


In [ ]:
#Indexing & Slicing

In [ ]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
m1[0]

0

In [ ]:
m1[-1]

11

In [ ]:
m1[[2,3,4,1,2,2]] #Fancy indexing

array([2, 3, 4, 1, 2, 2])

In [ ]:
m1[2,3,4,1,2,2] #6 dimension array

IndexError: too many indices for array: array is 1-dimensional, but 6 were indexed

In [ ]:
m1 = np.array([1,2,3,4,5,6,7,8,9,10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
m1[:5] #slicing

array([1, 2, 3, 4, 5])

In [ ]:
m1[-5:-1:-1]

array([], dtype=int64)

In [ ]:
import numpy as np
a = np.array([0,1,2,3,4,5])
a[4:] = 10
print(a)

[ 0  1  2  3 10 10]


In [ ]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a[4:]

array([4, 5])

In [ ]:
a[4:] = 10

In [ ]:
print(a)

[ 0  1  2  3 10 10]


In [ ]:
#Masking (Boolean masking)

In [ ]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
m1 < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [ ]:
m1[[ True,  True,  True,  True, False, False, False, False, False,
       False]]

array([1, 2, 3, 4])

In [ ]:
m1[m1%2 == 0]

array([ 2,  4,  6,  8, 10])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[2:] = b[::-1]
print(a)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])

In [ ]:
b[::-1]

array([6, 7, 8])

In [ ]:
a[2:]

array([3, 4, 5])

In [ ]:
a[2:] = b[::-1]

In [ ]:
a

array([1, 2, 6, 7, 8])

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])
a[3:] = b[::-2]
print(a)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([8,7,6])

In [ ]:
b[::-2]

array([6, 8])

In [ ]:
a[3:]

array([4, 5])

In [ ]:
a[3:] = b[::-2]

In [ ]:
a

array([1, 2, 3, 6, 8])

In [ ]:
#AirBnb
#NPS (Net Promoter Score)
#Net Promoter score = % Promoters - % Detractors

In [ ]:
!pip install --upgrade gdown
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 10.1MB/s]


In [ ]:
score = np.loadtxt('survey.txt', dtype ='int')

In [ ]:
type(score)

numpy.ndarray

In [ ]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [ ]:
score.shape

(1167,)

In [ ]:
#0-10 --> detractors --> 0-6
#neutral (7,8)

In [ ]:
#promoters --> >9

In [ ]:
detractors = score[score <= 6]

In [ ]:
score <= 6

array([False, False,  True, ...,  True, False, False])

In [ ]:
num_detractors = len(detractors)
num_detractors

332

In [ ]:
promoters = score[score >= 9]

In [ ]:
num_promoters = len(promoters)
num_promoters

609

In [ ]:
total = len(score)
total

1167

In [ ]:
percentage_detractors = (num_detractors/total) * 100
percentage_detractors

28.449014567266495

In [ ]:
percentage_promoters = (num_promoters/total) * 100
percentage_promoters

52.185089974293064

In [ ]:
nps = percentage_promoters - percentage_detractors
nps

23.73607540702657

In [ ]:
np.round(nps,2)

23.74

In [ ]:
score.max()

10

In [ ]:
score.min()

1

In [ ]:
np.min(score)

1